name: mp3_playlist
description: Aplicación de reproducción de música MP3 con streaming progresivo.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  path_provider: ^2.1.1
  flutter_downloader: ^1.11.5
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
